<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE iskola [
<!ELEMENT iskola (tanar, tantargy)>
<!ELEMENT tanar (nev, szak)>
<!ATTLIST tanar kod ID #REQUIRED>
<!ELEMENT nev (#PCDATA)>
<!ELEMENT szak (#PCDATA)>
<!ELEMENT tantargy (tnev, osztaly)>
<!ATTLIST tantargy kod IDREF #REQUIRED>
<!ATTLIST tantargy oktato CDATA #REQUIRED>
<!ELEMENT tnev (#PCDATA)>
<!ELEMENT osztaly (#PCDATA)>
]>

<iskola>
	<tanar kod="elso">
		<nev>Dr. Bednarik László</nev>
		<szak>GÉIK</szak>
	</tanar>
		
	<tanar kod="masodik">
		<nev>Dr. Házy Attila</nev>
		<szak>GÉIK</szak>
	</tanar>
	
	<tantargy kod="elso" oktato="Dr. Bednarik László">
		<tnev>Adatkezelés XML-ben</tnev>
		<osztaly>Harmadik osztály</osztaly>
	</tantargy>
</iskola> 